import React,{useMemo,useState} from 'react';
import {House,Receipt,PaperPlaneTilt,Headset,UserCircle,Bell,ArrowLeft,QrCode,Wallet,DotsThree,ShieldCheck,CheckCircle,Copy,ShareNetwork,MagnifyingGlass,SlidersHorizontal,ChatCircleDots,WarningCircle,Camera,FileText,LinkSimple,Phone,BookOpen,UsersThree,GearSix,Lock,Fingerprint,Key,DeviceMobile,Bank,Plus,SignOut,IdentificationCard,MapPin,CaretRight,Package,Eye,EyeSlash} from '@phosphor-icons/react';
import './mobile-exact.css';

const G='#0B8F52';
const txs=[
{id:'PP482910',item:'MacBook Air (Used)',amount:12500,status:'In Escrow',date:'14 Sep 2026',party:'Ama Serwaa'},
{id:'PP739201',item:'iPhone 14 Pro',amount:8200,status:'Completed',date:'10 Sep 2026',party:'Kofi Mensah'},
{id:'PP661028',item:'Nike Air Force 1',amount:1800,status:'Disputed',date:'08 Sep 2026',party:'Daniel K.'},
{id:'PP558774',item:'Sony WH-1000XM5',amount:2300,status:'Completed',date:'01 Sep 2026',party:'Kwame A.'}
];
const gh=n=>`GH₵ ${Number(n).toLocaleString('en-GH')}`;

function FingerprintLogo({compact=false}){return <div className={'pp-logo '+(compact?'compact':'')}><svg viewBox="0 0 72 72" aria-label="ProofPay logo mark"><g fill="none" stroke="currentColor" strokeWidth="4.3" strokeLinecap="round"><path d="M11 42c0-20 10-32 26-32 15 0 25 10 25 24 0 13-9 23-21 23"/><path d="M16 49V39c0-15 8-25 21-25 12 0 20 8 20 20 0 10-7 18-16 18"/><path d="M22 54V38c0-11 6-18 15-18 9 0 15 6 15 15 0 8-5 14-12 14"/><path d="M29 58V38c0-6 3-10 8-10 5 0 8 4 8 9"/></g><circle cx="39" cy="34" r="9" fill="#E6AF2E"/><text x="39" y="38" textAnchor="middle" fontSize="11" fontWeight="900" fill="#07553B">₵</text></svg><div><b>Proof<span>Pay</span></b><small>Pay Safe. Pay Smart.</small></div></div>}

function Nav({screen,setScreen}){const n=[['home',House,'Home'],['transactions',Receipt,'Transactions'],['send',PaperPlaneTilt,'Pay'],['support',Headset,'Support'],['profile',UserCircle,'Profile']];return <nav className="pp-nav">{n.map(([id,I,l])=><button key={id} onClick={()=>setScreen(id)} className={(screen===id?'active ':'')+(id==='send'?'pay':'')}><I weight={id==='send'?'fill':'regular'}/><span>{l}</span></button>)}</nav>}
function Shell({screen,setScreen,title='',children,back=false,logo=true}){return <div className="pp-stage"><div className="pp-device"><div className="pp-status"><b>9:41</b><span>▮▮ ◉ ▬</span></div><header className="pp-header">{back?<button className="pp-icon" onClick={()=>setScreen('home')}><ArrowLeft/></button>:logo?<FingerprintLogo compact/>:<span/>}<h2>{title}</h2><div className="pp-head-actions"><button className="pp-icon" onClick={()=>setScreen('notifications')}><Bell/><i/></button><div className="pp-avatar">EA</div></div></header><main className="pp-content">{children}</main><Nav screen={screen} setScreen={setScreen}/></div></div>}
function Btn({children,onClick,kind='primary'}){return <button className={'pp-btn '+kind} onClick={onClick}>{children}</button>}
function Status({children,type='green'}){return <span className={'pp-statuspill '+type}>{children}</span>}

function Auth({signup,setSignup,onDone}){const [show,setShow]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[pw,setPw]=useState('');return <div className="pp-auth-stage"><section className="pp-auth-card"><FingerprintLogo/><div className="pp-auth-art"><div className="pp-fingerprint-big"><Fingerprint weight="duotone"/><span>₵</span></div><h1>{signup?'Create your account':'Welcome back'}</h1><p>Pay safe. Pay smart.</p></div><form onSubmit={e=>{e.preventDefault();localStorage.setItem('pp_mobile_user',JSON.stringify({name:name||'Emmanuella Adu-Boahene',email}));onDone();}}>{signup&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label>}<label>Email or phone<input required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>Password<div className="pp-password"><input required minLength={6} type={show?'text':'password'} value={pw} onChange={e=>setPw(e.target.value)} placeholder="••••••••"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeSlash/>:<Eye/>}</button></div></label><Btn>{signup?'Create account':'Log in'}</Btn></form><p className="pp-auth-switch">{signup?'Already have an account?':'New to ProofPay?'} <button onClick={()=>setSignup(v=>!v)}>{signup?'Log in':'Sign up'}</button></p><div className="pp-safe"><ShieldCheck/>Protected by ProofPay security.</div></section></div>}

export function MobileExact(){
const [authed,setAuthed]=useState(()=>!!localStorage.getItem('pp_mobile_user'));const [signup,setSignup]=useState(false);const [screen,setScreen]=useState('home');const [amount,setAmount]=useState(8000);const [recipient,setRecipient]=useState('Ama Serwaa');const [tx,setTx]=useState(txs[0]);const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem('pp_mobile_user')||'{}')}catch{return {}}},[authed]);
if(!authed)return <Auth signup={signup} setSignup={setSignup} onDone={()=>setAuthed(true)}/>;
const go=s=>setScreen(s);
const screens={
home:<Shell screen={screen} setScreen={setScreen}><div className="pp-greeting"><div><span>Good morning,</span><h1>{(user.name||'Tega Abiola').split(' ')[0]} {(user.name||'Tega Abiola').split(' ')[1]||''}</h1><p>Here’s your account at a glance.</p></div></div><div className="pp-balance"><div className="pp-shield"><ShieldCheck weight="fill"/></div><div><small>Total Balance</small><strong>GHS 8,450.00</strong></div><button>›</button></div><div className="pp-quick four"><button onClick={()=>go('send')}><PaperPlaneTilt weight="fill"/><span>Send</span></button><button onClick={()=>go('receive')}><QrCode/><span>Receive</span></button><button><Wallet/><span>Top Up</span></button><button onClick={()=>go('settings')}><DotsThree/><span>More</span></button></div><div className="pp-section-title"><h3>Recent Activity</h3><button onClick={()=>go('transactions')}>See all</button></div><div className="pp-activity">{[['John Mensah','Payment sent','- GHS 250.00','Today, 10:24'],['Ama Serwaa','Payment received','+ GHS 1,200.00','Yesterday'],['Shop Basket','Purchase','- GHS 75.00','12 Sep'],['MTN MoMo Top Up','Top up','- GHS 100.00','10 Sep']].map((r,i)=><button key={r[0]} onClick={()=>go('transactions')}><span className="pp-round">{i===1?'↓':i===2?'🛒':i===3?'▰':'↗'}</span><span><b>{r[0]}</b><small>{r[1]}</small></span><span className={i===1?'plus':''}><b>{r[2]}</b><small>{r[3]}</small></span></button>)}</div></Shell>,
send:<Shell screen={screen} setScreen={setScreen} title="Send Payment" back><p className="pp-subtitle">Send money quickly and securely.</p><h4>Send to</h4><div className="pp-tabs three"><button className="on">Contact</button><button>Phone</button><button>Bank</button></div><div className="pp-search"><MagnifyingGlass/><input placeholder="Search contacts"/></div><div className="pp-contact-list">{[['JM','John Mensah','+233 24 123 4567'],['AS','Ama Serwaa','+233 20 987 6543'],['DK','Daniel Kwarteng','+233 54 321 0987'],['EA','Emily Asante','+233 26 555 0101']].map((c,i)=><button key={c[1]} onClick={()=>setRecipient(c[1])}><span>{c[0]}</span><div><b>{c[1]}</b><small>{c[2]}</small></div><i className={recipient===c[1]?'chosen':''}/></button>)}</div><label>Amount<div className="pp-money-input"><b>GHS</b><input type="number" value={amount} onChange={e=>setAmount(+e.target.value)}/></div></label><div className="pp-note-input"><ChatCircleDots/><span>Add a note (optional)</span></div><Btn onClick={()=>go('review')}>Send Payment <CaretRight/></Btn></Shell>,
receive:<Shell screen={screen} setScreen={setScreen} title="Receive Payment" back><p className="pp-subtitle">Share your details to receive money.</p><div className="pp-tabs two"><button className="on"><QrCode/> QR Code</button><button><UserCircle/> My Details</button></div><div className="pp-qr"><QrCode weight="duotone"/><div className="pp-qr-logo"><FingerprintLogo compact/></div></div><h3 className="center">Tega Abiola</h3><p className="center muted">+233 24 123 4567</p><div className="pp-circle-actions"><button><ShareNetwork/><span>Share</span></button><button><FileText/><span>Download</span></button></div><div className="pp-safe"><ShieldCheck/> <div><b>Receive money securely</b><span>Share your QR code or account details with trusted people only.</span></div></div></Shell>,
review:<Shell screen={screen} setScreen={setScreen} title="Review Transaction" back><div className="pp-product"><div className="pp-product-img">💻</div><div><b>MacBook Air (Used)</b><small>Electronics · Used<br/>Qty: 1</small></div><strong>{gh(amount)}</strong></div><div className="pp-people"><div><small>Buyer</small><b>Kofi Mensah</b><span>Accra, Ghana</span></div><div><small>Seller</small><b>{recipient}</b><span>Kumasi, Ghana</span></div></div><div className="pp-summary"><p><span>Amount</span><b>{gh(amount)}</b></p><p><span>Escrow fee (1%)</span><b>{gh(amount*.01)}</b></p><p><span>Total (held in escrow)</span><strong>{gh(amount*1.01)}</strong></p></div><div className="pp-lines"><p><span>▣ Expected delivery</span><b>16 Sep 2026</b></p><p><span>▢ Release to seller</span><b>After you confirm delivery</b></p></div><Btn onClick={()=>go('momo')}>Confirm Transaction <CaretRight/></Btn></Shell>,
momo:<Shell screen={screen} setScreen={setScreen} title="MoMo Authorization" back><div className="pp-wallet-card"><div className="pp-mtn">MTN</div><div><b>MTN MoMo</b><small>+233 24 123 4567</small></div><CaretRight/></div><div className="pp-summary"><p><span>Amount</span><b>{gh(amount)}</b></p><p><span>Escrow fee (1%)</span><b>{gh(amount*.01)}</b></p><p><strong>Total to pay</strong><strong>{gh(amount*1.01)}</strong></p></div><div className="pp-otp-title"><Lock/><div><b>Enter MoMo OTP</b><small>A 6-digit code has been sent to your phone.</small></div></div><div className="pp-otp">{[1,4,7,2,9,0].map((n,i)=><input key={i} readOnly value={n}/>)}</div><p className="center muted">Didn’t receive code? <b className="green">Resend in 28s</b></p><Btn onClick={()=>go('success')}>Authorize Payment <CaretRight/></Btn></Shell>,
success:<Shell screen={screen} setScreen={setScreen} title="" back={false}><div className="pp-success"><ShieldCheck weight="fill"/></div><h1 className="center">Payment Successful!</h1><p className="center muted">Your payment has been secured in escrow.</p><div className="pp-summary"><p><span>Transaction ID</span><b>#PP482910</b></p><p><span>Amount</span><b>{gh(amount)}</b></p><p><span>Payment method</span><b>MTN MoMo</b></p></div><div className="pp-safe"><Lock/><span>We’ll notify you when the item is delivered and ready for release.</span></div><Btn onClick={()=>go('transaction-details')}>View Transaction <CaretRight/></Btn><Btn kind="outline" onClick={()=>go('home')}>Go Home</Btn></Shell>,
transactions:<Shell screen={screen} setScreen={setScreen} title="Transactions"><p className="pp-subtitle">Track, manage and resolve your trades.</p><div className="pp-search"><MagnifyingGlass/><input placeholder="Search transactions"/><SlidersHorizontal/></div><div className="pp-chips"><button className="on">All</button><button>In Escrow</button><button>Completed</button><button>Disputed</button></div><div className="pp-tx-list">{txs.map(t=><button key={t.id} onClick={()=>{setTx(t);go('transaction-details')}}><span className="pp-thumb">{t.item.includes('Mac')?'💻':t.item.includes('iPhone')?'📱':t.item.includes('Nike')?'👟':'🎧'}</span><span><b>{t.item}</b><small>#{t.id}<br/>{t.date}</small></span><span><b>{gh(t.amount)}</b><Status type={t.status==='Disputed'?'red':'green'}>{t.status}</Status></span><CaretRight/></button>)}</div></Shell>,
 'transaction-details':<Shell screen={screen} setScreen={setScreen} title="Transaction Details" back><div className="pp-product"><div className="pp-product-img">💻</div><div><b>{tx.item}</b><small>#{tx.id}<br/>Electronics · Used</small></div><div><Status>In Escrow</Status><strong>{gh(tx.amount)}</strong></div></div><div className="pp-people detailed"><div><small>Buyer</small><b>Kwame A.</b><span>★★★★★ 4.8</span></div><div className="swap">⇄</div><div><small>Seller</small><b>Ama S.</b><span>★★★★★ 4.9</span></div></div><h4>Transaction Progress</h4><div className="pp-progress"><span className="done">Payment<br/>Received</span><span className="done">In Escrow</span><span>Out for Delivery</span><span>Completed</span></div><div className="pp-summary"><p><span>Item price</span><b>{gh(tx.amount)}</b></p><p><span>Protection fee (2%)</span><b>{gh(tx.amount*.02)}</b></p><p><strong>Total</strong><strong>{gh(tx.amount*1.02)}</strong></p></div><div className="pp-two"><Btn kind="outline" onClick={()=>go('messages')}><ChatCircleDots/> Message</Btn><Btn kind="danger" onClick={()=>go('dispute')}><WarningCircle/> Dispute</Btn></div><Btn onClick={()=>go('release')}>Release Payment</Btn></Shell>,
release:<Shell screen={screen} setScreen={setScreen} title="Release Payment" back><div className="pp-delivery"><div>📦<CheckCircle weight="fill"/></div><h2>Delivery Verified</h2><p>The item has been delivered and confirmed by the buyer.</p></div><h3>Release Summary</h3><div className="pp-product compact"><div className="pp-product-img">💻</div><div><b>{tx.item}</b><small>#{tx.id}</small></div><strong>{gh(tx.amount)}</strong></div><div className="pp-summary"><p><span>Item price</span><b>{gh(tx.amount)}</b></p><p><span>Protection fee (2%)</span><b>{gh(tx.amount*.02)}</b></p><p><strong>Total to release</strong><strong>{gh(tx.amount)}</strong></p></div><div className="pp-safe"><ShieldCheck/><span>Funds will be released to the seller’s ProofPay wallet instantly.</span></div><Btn onClick={()=>{alert('Demo: payment released');go('transactions')}}><PaperPlaneTilt/> Release Funds</Btn></Shell>,
dispute:<Shell screen={screen} setScreen={setScreen} title="File a Dispute" back><p className="pp-subtitle">Let us know what’s wrong. We’ll review it quickly.</p><h4>What’s the issue?</h4><div className="pp-issue-grid">{[['Item not received',Package],['Item not as described',Package],['Unauthorized payment',Wallet],['Refund issue',Receipt],['Damaged item',WarningCircle],['Other issue',DotsThree]].map(([t,I],i)=><button className={i===0?'on':''} key={t}><I/><span>{t}</span>{i===0&&<CheckCircle weight="fill"/>}</button>)}</div><label>Add a short description<textarea placeholder="Tell us what happened..."/></label><h4>Add evidence (optional)</h4><div className="pp-evidence"><button><Camera/>Photo</button><button><FileText/>Document</button><button><LinkSimple/>Link</button><button><DotsThree/>More</button></div><Btn onClick={()=>{alert('Dispute submitted');go('messages')}}>Submit Dispute</Btn></Shell>,
messages:<Shell screen={screen} setScreen={setScreen} title="Messages"><p className="pp-subtitle">Your conversations with our support team.</p><div className="pp-search"><MagnifyingGlass/><input placeholder="Search messages"/><SlidersHorizontal/></div><div className="pp-messages">{[['ProofPay Support','We’ve received your dispute.','10:24 AM',2],['Jane (Support)','Here’s an update on your case.','Yesterday',1],['Dispute #PP482910','We need a bit more information.','12 Sep',1],['Account & Security','Tips to keep your account safe.','10 Sep',0],['Daniel (Support)','Your issue has been resolved.','8 Sep',0],['Payments Team','Your refund has been processed.','5 Sep',0]].map(([n,m,d,c],i)=><button key={n}><span className="pp-msg-avatar">{i===1?'👩🏾':i===4?'👨🏾':'◉'}</span><span><b>{n}</b><small>{m}</small></span><span><small>{d}</small>{c>0&&<i>{c}</i>}</span></button>)}</div></Shell>,
support:<Shell screen={screen} setScreen={setScreen} title="Agents & Support"><p className="pp-subtitle">Get help the way that works for you.</p><div className="pp-support-grid"><button><ChatCircleDots/><b>Live Chat</b><span>Chat with our team</span><CaretRight/></button><button><BookOpen/><b>Help Center</b><span>Find answers</span><CaretRight/></button><button><Phone/><b>Call Support</b><span>Speak to an agent</span><CaretRight/></button><button><UsersThree/><b>Find an Agent</b><span>In your area</span><CaretRight/></button></div><div className="pp-escalate"><ShieldCheck/><span><small>NEED MORE HELP?</small><b>Escalate Your Case</b></span><button>→</button></div><div className="pp-hours"><span>◷</span><div><b>Support Hours</b><small>Mon – Sun, 8:00 AM – 8:00 PM (WAT)</small></div></div></Shell>,
notifications:<Shell screen={screen} setScreen={setScreen} title="Notifications"><div className="pp-chips"><button className="on">All</button><button>Payments</button><button>Security</button><button>Support</button></div><div className="pp-notifications">{[[Package,'Payment released','Your payment of GH₵8,000 has been released to the seller.','2m ago'],[Fingerprint,'In review','Your identity verification is under review.','1h ago'],[Receipt,'Payment received','You received GH₵5,000 from John D.','3h ago'],[Headset,'Support update','Your support ticket has been updated.','3h ago'],[Bell,'New feature','You can now pay with mobile money across Africa!','1d ago']].map(([I,t,s,d],i)=><div key={t} className={'n n'+i}><span><I/></span><div><b>{t}</b><small>{s}</small></div><em>{d}</em></div>)}</div></Shell>,
profile:<Shell screen={screen} setScreen={setScreen} title="Profile"><div className="pp-profile-hero"><div className="pp-profile-photo">EA</div><div><h2>{user.name||'Tega Abiola'}</h2><span>{user.email||'tega.abiola@example.com'}</span><Status>✓ Verified</Status></div><button>›</button></div><div className="pp-profile-stats"><div><span>▣</span><b>₵ 124,500</b><small>Total Volume</small></div><div><span>✓</span><b>12</b><small>Successful Trades</small></div></div><div className="pp-menu">{[[UserCircle,'Personal Information'],[ShieldCheck,'Verification & Security','kyc'],[Wallet,'Payment Methods','wallets'],[GearSix,'Preferences','settings'],[Headset,'Help & Support','support']].map(([I,t,to])=><button key={t} onClick={()=>to&&go(to)}><I/><span><b>{t}</b><small>{t==='Payment Methods'?'Bank accounts, mobile money':t==='Preferences'?'Language, notifications':t==='Help & Support'?'Get help, contact us':'Name, email, phone'}</small></span><CaretRight/></button>)}</div><button className="pp-logout" onClick={()=>{localStorage.removeItem('pp_mobile_user');setAuthed(false)}}><SignOut/>Log Out</button></Shell>,
kyc:<Shell screen={screen} setScreen={setScreen} title="Verification" back><div className="pp-review-badge">◷ In review</div><p className="pp-subtitle">Complete your verification to unlock all features and trade with confidence.</p><div className="pp-kyc-list">{[[IdentificationCard,'Personal Information','Full name, date of birth, nationality','Completed'],[FileText,'ID Verification','Upload a valid ID','Completed'],[UserCircle,'Selfie Check','Take a live selfie','In review'],[MapPin,'Address Proof','Upload proof of address','Not started']].map(([I,t,s,st],i)=><div key={t}><span className={'pp-step '+(i<2?'done':i===2?'review':'')}>{i<2?'✓':i+1}</span><I/><span><b>{i+1}. {t}</b><small>{s}</small></span><Status type={st==='In review'?'gold':st==='Not started'?'gray':'green'}>{st}</Status></div>)}</div><div className="pp-community"><div><h3>A Safer Community<br/>Starts with You</h3><p>Verification helps us keep our platform safe for everyone.</p></div><ShieldCheck weight="fill"/></div></Shell>,
settings:<Shell screen={screen} setScreen={setScreen} title="Settings"><p className="pp-subtitle">Manage your account and preferences.</p><h4>Security</h4><div className="pp-menu simple">{[[Lock,'Biometric Login',true],[ShieldCheck,'Two-Factor Authentication',true],[Key,'Change PIN',false],[DeviceMobile,'Manage Devices',false]].map(([I,t,tog])=><button key={t}><I/><span><b>{t}</b><small>{t.includes('Biometric')?'Use Face ID or Touch ID':t.includes('Factor')?'Add an extra layer of security':''}</small></span>{tog?<i className="pp-toggle on"/>:<CaretRight/>}</button>)}</div><h4>Notifications</h4><div className="pp-menu simple">{[['Transaction Alerts'],['Promotions & Updates']].map(([t])=><button key={t}><Bell/><span><b>{t}</b><small>{t==='Transaction Alerts'?'Get notified about your activity':'Product news and offers'}</small></span><i className="pp-toggle on"/></button>)}</div><h4>More</h4><div className="pp-menu simple"><button onClick={()=>go('support')}><Headset/><span><b>Help & Support</b></span><CaretRight/></button><button><FileText/><span><b>Terms & Privacy</b></span><CaretRight/></button></div></Shell>,
wallets:<Shell screen={screen} setScreen={setScreen} title="Wallet & Payment Methods" back><p className="pp-subtitle">Link and manage your accounts for seamless payments.</p><h4>Mobile Money</h4>{[['MTN','MTN MoMo','+233 24 123 4567','GHS 1,240.50','mtn'],['t','Telecel Cash','+233 20 987 6543','GHS 856.00','tel'],['A','AT Money','+233 55 112 3344','GHS 320.75','at']].map(([l,n,p,b,c])=><div className="pp-payment-row" key={n}><span className={c}>{l}</span><div><b>{n}</b><small>{p}</small></div><div><Status>Active</Status><b>{b}</b></div><CaretRight/></div>)}<h4>Bank Account</h4><div className="pp-payment-row"><span className="bank"><Bank/></span><div><b>Stanbic Bank Ghana</b><small>•••• 5678</small></div><Status>✓ Verified</Status><CaretRight/></div><button className="pp-add"><Plus/> Link another payment method <CaretRight/></button></Shell>,
ussd:<Shell screen={screen} setScreen={setScreen} title="USSD Access" back><p className="pp-subtitle">Quick, simple and secure payments anytime, anywhere.</p><div className="pp-ussd-hero"><DeviceMobile/><div><small>Dial</small><h1>*719#</h1><span>to access ProofPay</span></div><ul><li>Pay safely</li><li>Trade easily</li><li>No internet needed</li></ul></div><h4>USSD Menu Preview</h4><pre>Welcome to ProofPay{`\n`}1. Make Payment{`\n`}2. Approve Release{`\n`}3. Check Status{`\n`}4. My Account{`\n`}5. Help{`\n\n`}Reply with your choice (1-5): _</pre><h4>Quick Actions</h4><div className="pp-ussd-actions"><button><PaperPlaneTilt/><b>Create Payment</b><span>Initiate a transaction</span></button><button><CheckCircle/><b>Approve Release</b><span>Confirm payment</span></button><button><MagnifyingGlass/><b>Check Status</b><span>Track your transaction</span></button><button><Headset/><b>Get Help</b><span>USSD support</span></button></div></Shell>
};return screens[screen]||screens.home;
}
